name: dev_task_adorni
description: Dev Task Easypol - Gabor Adorni

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4
  http: ^0.13.4
  local_auth: ^1.1.8
  path_provider: ^2.0.5
  permission_handler: ^8.2.5
  pin_code_fields: ^7.3.0
  provider: ^6.0.1
  qr_code_scanner: ^0.5.2
  qr_flutter: ^4.0.0
  share_plus: ^3.0.4
  shared_preferences: ^2.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher/cocktail_icon.png"
  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/launcher/cocktail_adaptive.png"

flutter_native_splash:
  color: "#212121"
  image: "assets/launcher/cocktail_splash.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
